### ISSUE TITLE
Notes about testing Titan V on Macos: mostly OK.. 

### ISSUE THREAD

**Issue by oscarbg** [ogiroux/freestanding#1]
Hi,
just after reading "https://devblogs.nvidia.com/cuda-turing-new-gpu-compute-possibilities" I became aware of your Cppcon talk and how advanced / improved Volta and later archs. are for C++..
impressed to see a mac.sh..
can share if you already tried on MacOS or script is only for future purposes?
I say as currently there are no drivers for Volta or newer GPUs for MacOS..
or they are? really I found Nvidia Web Driver - 387.10.10.15.15.108 supports Titan V and altough Nvidia removed from web shortly after posting I was able to gather the driver from some good soul on the Internet..
I tested on High Sierra + Xcode 9.4+CUDA 10 and it works OK
I had to do only 2 changes:
1) so I updated build script to point to /Developer/NVIDIA/CUDA-10.0/bin/nvcc
2) I removed  --compiler-bindir /usr/local/opt/llvm@5/bin/clang totally..
seems to work ok without it.. can point why it's needed?

also another question is I see :

<simt/cstdalign> | Except Mac OS X. | <stdalign.h>

can share what's unique in MacOS to not support it?

thanks..
Oscar.

**Comment by ogiroux** [comment]
There isn't much I can say about this. I wish I could.

Your 2 changes make sense. At the time I pushed that version, NVCC didn't work with the Clang version that came with Xcode, so that's why you see LLVM-5 line there. I sort-of leaked what I had in my development environment at the time.

The only reason <cstdalign> isn't supported is that Mac OS X doesn't have the underlying header. I don't know why. There's barely anything that is declared by this header.

**Comment by oscarbg** [comment]
thanks for comments.. make sense..
closing..

**Comment by teerachat67** [comment]
Hello . I am new user of github. I searched and read your topic and I have problem with the installation of eGPU Titan V. I use Imac 2017 Mac os High sierra 10.13.6 and I want to connect eGPU for my molecular dynamic simulation for my Ph.D project. But I cannot file a NVIDIA to support Titan V. Could you please send me a driver file through my e-mail “teerachat.saeheng@gmail.com”?

Thank you in advance

**Comment by ogiroux** [comment]
No. This is not an appropriate channel to ask for this. You can engage with the folks on https://devtalk.nvidia.com with issues like this one.

Sorry, Olivier.

**Comment by teerachat67** [comment]
Dear Oliver

Thank you

Regards
Teerachat

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
